### ISSUE TITLE
test cdn

### ISSUE THREAD

**Issue by aventurini** [ECTRLSOLUTIONS/d40cdn#1]
configurare cartelle
d40/js, css.
zainetto/js, css
common/js, css.

gli ftl restano nei progetti specifici. Se usano questi js, si mette nel readme.

provare test cdn:
https://gomakethings.com/how-to-turn-any-github-repo-into-a-cdn/

da provare le modifiche come funzionano

**Comment by dariocavada** [comment]
Provato CDN e aggiornato il readme.MD che mostra due esempi per l'accesso ai file di questo repo tramite CDN.
Per lo sviluppo occorre necessariamente utilizzare direttamente git (esempio sempre nel readme.MD)

**Ricordiamoci che questo repo è leggibile da tutti senza alcun accesso !!! Anche le issue e il Wiki.**

**Comment by aventurini** [comment]
ho fatto dei test qui:
https://editor.d40.it/web/d40owner-demo-developer/navigazione-circolare

jsdeliver funziona.


amazon CDN non funziona per via del cross origin. Ho provato a vedere se c'e' un modo di forzare da CDN l'header ma non l'ho trovato.

accesso diretto a github non funziona, sempre per via del cross origin. 
Assumendo di usare jsdeliver, resta da risolvere come fare per lo sviluppo. Ci associamo una cartella dedicata allo sviluppo che scrive in un bucket dedicato s3 ?

**Comment by aventurini** [comment]
lo riprendo, sto provando con un proxy

**Comment by dariocavada** [comment]
Ho creato un piccolo proxy nodejs, casomai sarebbe da mettere su uno dei nostri server:

https://github.com/ECTRLSOLUTIONS/d40cdn/blob/main/proxy.js

**Comment by aventurini** [comment]
l'hai provato accedendo  qui ?:
 https://raw.githubusercontent.com/ECTRLSOLUTIONS/d40cdn/
ho provato un  proxy su apache (non il tuo) e mi dà errore sull'ssl.

**Comment by dariocavada** [comment]
Sì esatto, io ho provato utilizzando localhost...

Se ti metti nella cartella d40cdn e lanci:

`node proxy.js`
 
Viene avviato il proxy.

A questo punto puoi accedere ai file tramite URL:

[http://localhost:8000/ECTRLSOLUTIONS/d40cdn/main/common/js/suggesto.js](http://localhost:8000/ECTRLSOLUTIONS/d40cdn/main/common/js/suggesto.js)

**Comment by dariocavada** [comment]
... con SSL non ho provato. 
Probabile non vada la versione che ho fatto io.

**Comment by dariocavada** [comment]
Forse qui ci sono delle indicazioni per la creazione di un proxy con https:

https://www.vanamco.com/2014/06/24/proxy-requests-in-node-js/

**Comment by aventurini** [comment]
ho configurato apache sul proxy che hai fatto tu e funziona:

https://cdngit.d40.it/ECTRLSOLUTIONS/d40cdn/main/common/js/suggesto.js

manca il forevever per evitare che cada. sarebbe da aggiungere un controllo che possa fare il prxy solo di ECTRLSOLUTIONS/d40cdn

**Comment by aventurini** [comment]
non funziona il CORS

https://editor.d40.it/web/d40owner-demo-developer/navigazione-circolare

ho provato anche a impostare da apache vari flag, ad esempio:
  Header set Access-Control-Allow-Origin "*"
  Header always set Access-Control-Allow-Headers: "origin, content-type, accept, authorization"
  Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
  Header unset X-Frame-Options


ma non funziona lo stesso. 
proverò ancora

**Comment by dariocavada** [comment]
Dov'è che posso vedere l'errore CORS ?

**Comment by aventurini** [comment]
qui:

https://editor.d40.it/web/d40owner-demo-developer/navigazione-circolare

devi prima loggarti qui:
https://editor.d40.it/ (d40owner)

**Comment by dariocavada** [comment]
Invece di forever ultimamente ho provato `pm2` (lo stesso servizio che utilizzo per il museo della guerra)

Si installa `pm2` con `npm`:

`$ npm install pm2 -g`

Si fa partire l'applicazione: 
`$ pm2 start app.js`

Per monitorarne lo stato, start stop e altri comandi:
https://github.com/Unitech/pm2

**Comment by aventurini** [comment]
messo anche pm2

esempio di link tramite cdn amazon:
https://d2m98g73xnllun.cloudfront.net/ECTRLSOLUTIONS/d40cdn/main/dms/js/navcircvueapp.js

esempio di link  diretto: https://cdngit.d40.it/ECTRLSOLUTIONS/d40cdn/main/dms/js/navcircvueapp.js

aggiunto anche redirect 301 se un url richiesto non è del tipo /ECTRLSOLUTIONS/d40cdn.
mi sembra a posto tutto adesso, chiudo e passo anche a te dario cosi vedi

**Comment by aventurini** [comment]
allora usiamo per produzione questo metodo (cdn amazon su nostro proxy che va su raw.github). 5 minuti di latenza.
per sviluppo, sync su una cartella dedicata per sviluppatore in s3, bucket mkspresstage. Esempio:
https://s3-eu-west-1.amazonaws.com/mkspresstage.suggesto.eu/adriano/common/js/suggesto.js -> sviluppo
https://d2m98g73xnllun.cloudfront.net/ECTRLSOLUTIONS/d40cdn/main/common/js/suggesto.js produzione
vedi pagina readme.md
