### ISSUE TITLE
Mappa - formato GPX non compatibile

### ISSUE THREAD

**Issue by dariocavada** [ECTRLSOLUTIONS/d40cdn#2]
Alcuni formati GPX non sono compatibili con l'attuale libreria utilizzata (Omnivore).
Occorre utilizzare un altra libreria solo per GPX perché Omnivore non viene più mantenuta da 5 anni.

La nuova libreria da integrare:
https://github.com/mpetazzoni/leaflet-gpx

**Comment by aventurini** [comment]
si può convertire il file ?

**Comment by dariocavada** [comment]
Già detto a Nicola:

caricare (Load GPX) il file GPX che non funziona e poi Export e scarichi il nuovo GPX, che funziona ...

https://gpx.studio/
